.PHONY: run

PYTHON ?= .venv/bin/python
LOCAL_ENV = CADQUERY_WORKER_TIMEOUT_SECONDS=120 XDG_CACHE_HOME=$(CURDIR)/.cache PYTHONDONTWRITEBYTECODE=1

run:
	$(LOCAL_ENV) $(PYTHON) -m uvicorn app.main:app --host 127.0.0.1 --port 8852
